### PR TITLE
implement html lazy function for react renderer

### PR DESCRIPTION
**Pull request by minedeljkovic**
This is a port of http://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html-Lazy

### CODE REVIEW

**Comment by minedeljkovic** [comment]
Examples of usage (I used them for quick manual test, and did not want to include them in main branch) are [here](https://github.com/minedeljkovic/elm-ts/blob/lazy-examples/examples/All.tsx) and [here](https://github.com/minedeljkovic/elm-ts/blob/lazy-examples/examples/LazyTest.tsx)

**Comment by gcanti** [comment]
Hi @minedeljkovic,

since we are dealing with React, can't you just memoize the `view` function and/or use `shouldComponentUpdate` (or even `PureComponent`) in your components in order to optimize re-renderings?

**Comment by minedeljkovic** [comment]
Yes, this function does both, and I believe with minimal boilerplate. Let me explain.

If you decide to use PureComponent, you would have to wrap every React element expression that is result of Html function (I will skip the details of a Reader) inside it's own Component, leaving the view function as a mere props passing function (boilerplate):
```js
// Counter example

// Model, init, Msg, update ....

class Counter extends React.PureComponent<{ dispatch: Dispatch<Msg>, model: Model }, {}> {
  render() {
    const { dispatch, model } = this.props;
    return (
      <div>
        Count: {model}
        <button onClick={() => dispatch({ type: 'Increment' })}>+</button>
        <button onClick={() => dispatch({ type: 'Decrement' })}>-</button>
      </div>
    );
  }
}

export function view(model: Model): Html<Msg> {
  return new Reader(dispatch => <Counter model={model} dispatch={dispatch} />);
}
```
Aside from boilerplate, I believe this approach has two more negative sides:
  1. This resulting component is always Pure, even if composing view function (from some other module) does composition in a way that model is always changed. I believe this should be controlled from composing side.
  2. You would have to be sure that dispatch function stays the same. It is OK for top level dispatch function, but if you do any kind of decomposition of top level view function, that includes calling lower level view functions with adapted dispatch, you need to make sure to memoize function that produces that adapted dispatch (boilerplate).

The other option you mentioned is to memoize curried view function (still skipping details of a Reader). If you memoize only the first function, you would get the same Html function that still needs to be run with the dispatch, and you will evaluate React element expression, even though it's value should stay the same. If you decide to memoize on both first function arguments and dispatch argument (including negative side no. 2 from above) you would get the same React element, but React reconciler would anyway process it unless it is PureComponent. So this second option saves you only from evaluating React element expression inside Html function.

This implies you need both approaches to be fully memoized, and with extra little downside that you shallowly compare view arguments and dispatch values twice.

These are approaches I believe you pointed me to. Please, let me know if you had some other strategy in mind.

**Comment by gcanti** [comment]
> you would have to wrap every React element expression that is result of Html function (I will skip the details of a Reader) inside it's own Component

I mean that, since we are dealing with React, I'd rather leverage React's component system, i.e. only one top level `view` function per application, as I did here (not optimized) https://github.com/gcanti/elm-ts-todomvc/blob/d53288019f9cab3d0dba777cfc279b39e9bbf48d/src/App.tsx#L466

**Comment by minedeljkovic** [comment]
You cannot simply leverage React's PureComponent here since `onFinish, onChange, ..., onClearCompleted` callbacks would all give different prop values to AppComponent on each `view` invocation

**Comment by gcanti** [comment]
Right, I'm using functional components there (that's way I wrote "not optimized")

However this looks like a common problem in the React world, I guess there are many possible solutions.

For example, in that specific case and since `dispatch` never changes, I could memoize the handlers https://github.com/gcanti/elm-ts-todomvc/blob/b55a89dd6e6b9dffc8ba668f3fc3392ca50931e4/src/App.tsx#L467

**Comment by minedeljkovic** [comment]
>  since dispatch never changes

Not necessarily. If that view function is passed to `Program` (i.e. top view function) dispatch never changes, but if that view function is composed inside another view function you typically transform top level dispatch before passing it like so:
https://github.com/minedeljkovic/elm-ts/blob/26072a0342a10c9899a526a45e69d320e84365da/examples/All.tsx#L89

Now I have to memoize all those dispatch transforming functions, right?
And further up to the top, wherever you miss to memoize dispatch transforming function, you loose memoization below.

And if you don't miss anything, I still believe that memoization needs to be controlled from where the view function is called, not where it is defined. For example, if you use
https://github.com/gcanti/elm-ts-todomvc/blob/b55a89dd6e6b9dffc8ba668f3fc3392ca50931e4/src/App.tsx#L479
as a top level view funciton passed to `Program` memoization is an overhead, because model is never the same.

**Comment by gcanti** [comment]
> Now I have to memoize all those dispatch transforming functions, right?

Right

> And further up to the top, wherever you miss to memoize dispatch transforming function, you loose memoization below.

Right, that's a common concern in any React application though

> because model is never the same

If model is never the same, using `lazy` looks even more expensive

Don't get me wrong, I'm not saying that `lazy` couldn't be useful, I just don't see why it should be a "blessed" solution in elm-ts, there are many other solutions to this common problem which depends on the particular application at hand

In conclusion, I think I would prefer to keep it external to the core library

**Pull request closed without merging**
