### PR TITLE
Re-add map to Sub and Html and remove Reader, fix #12

### LINKED ISSUE #12: Removing of map function from Html and Sub module
In [this commit](https://github.com/gcanti/elm-ts/commit/e971553d54dfe7e831e430d2892e42c72ab65142#diff-3d86db7c4d764c13d9926ad29b24f1b9) `map` function was removed from `Html` and `Sub` modules.

In original Elm architecture `Sub`, `Cmd` and `Html` are effects that result in a parametric type `Msg`. Idiomatic way of composing `Sub` and `Cmd` effects in Elm architecture are `batch` and `map` and way of composing Html effect is `map`.

This issue is really a question. Why `map` function was removed from Sub and Html?

Of course, `map` over `Sub` is easy to achieve, because `Sub` is really `Observable` which has its own `map` method, but maybe `Observable` should be treated as an implementation detail here (the same way it's treated in `batch` function).

Elm's way of `map` over `Html` is also achievable:
```js
view(model).run(a => dispatch(f(a))
```
Introduction of a `Reader` as a structure for `Html` is, I believe, in collision with original Elm's `Html` effect. `map` of a elm-ts's `Html` (in fact a `Reader`) effect maps function `dom => dom` (I cannot see straight away where would that be usable, since using different renderers is probably not a good idea) while `map` of a Elm's `Html` function maps function `msg => msg`.

### PR DESCRIPTION
**Pull request by minedeljkovic**
This fixes #12

### CODE REVIEW

**Comment by minedeljkovic** [comment]
Oh, I see. But wouldn't it be confusing that `map` of `Html` is fundamentally different than `map` of `Reader`, even though `Html` is a `Reader` in every other way?

May I ask, what benefit are you seeing in `Html` being a `Reader`?
If I can get to that, I might rethink all that I said in the issue.

**Comment by minedeljkovic** [comment]
@gcanti if your only concern is that it's a breaking change, it could sit for a while.
There are obvious ways around the issue, and I'm really focused on #3 working on integration with [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension), so some more issues might come up (although I don't expect it. It's really smooth from elm-ts's side, but I'm running into lots of small issues from redux-devtools-extension's side :( )

**Comment by gcanti** [comment]
Ok, in the meanwhile I'll think about this

> May I ask, what benefit are you seeing in Html being a Reader?

and try to come up with a decent example

**Comment by gcanti** [comment]
> try to come up with a decent example

I give up, in the end all my examples are a bit silly. Let's remove `Reader` and prepare version 0.4.

Speaking of which, what about swapping the arguments of all `map`s for a better DX?

```ts
export declare function map<a, msg>(ha: Html<a>, f: (a: a) => msg): Html<msg>
//                                                      ^ better type inference here
```

instead of

```ts
export declare function map<a, msg>(f: (a: a) => msg ha: Html<a>): Html<msg>
```

Also, is there a reason why you changed `Html.Html<dom, msg>` and `React.Html<msg>` from `interface` to `type`?

**Comment by minedeljkovic** [comment]
> what about swapping the arguments of all maps for a better DX?

No automatic currying and pipeline operator in JS (yet), so no harm would be done.
(just curious, is the importance of parameters order just some glitch in Typescript type inference? Is there an existing issue? I am just switching from `flow`, so glitches are not unfamiliar :) )

>  is there a reason why you changed Html.Html<dom, msg> and React.Html<msg> from interface to type

Three reasons:
1. It was a type before switching it to `Reader`
2. It's just a function. 
3. I am switching from flow to Typescript, and still learning some Typescript specifics

**Comment by gcanti** [comment]
@minedeljkovic let me know if you want me to release 0.4 or you got any more changes

**Comment by minedeljkovic** [comment]
@gcanti I'm still fiddling with some debugging scenarios using [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension), and it could take a while.
OTOH, I think 0.4 is conceptually 100% equal to elm 0.18, elm 0.18 has a [great debugger](http://elm-lang.org/blog/the-perfect-bug-report), so I don't see any significant changes (especially breaking ones) needed to support those scenarios.

**Comment by gcanti** [comment]
@minedeljkovic released 0.4 (and updated `elm-ts-todomvc`) 

Thanks

**Pull request merged**
