### PR TITLE
Original XMLHttpRequest object in response

### PR DESCRIPTION
**Pull request by bmazzarol**
@StefanoMagrassi I added the xhr to the response object via the new sendFull function as per the other PR.

The only issue I can see is that the Error state can't get access to it. Not sure how much of an issue that is.

### CODE REVIEW

**Comment by StefanoMagrassi** [comment]
@gcanti what do you think about this PR? It seems ok to me

**Comment by gcanti** [comment]
@bmazzarol @StefanoMagrassi `Response` already contains a `headers` field

```ts
export interface Response<Body> {
  url: string
  status: {
    code: number
    message: string
  }
  headers: Record<string, string>
  body: Body
}
```

however looks like there's a bug here https://github.com/gcanti/elm-ts/blob/0ae79d05427bfc0e433bbdef224a9180e24beb61/src/Http.ts#L144

**Comment by StefanoMagrassi** [comment]
@bmazzarol after talking with @gcanti about the `Response` headers bug, I decided to open a new PR (#50) which fixes the issue without exposing the underlying `XMLHttpRequest` object (that is a kind of implementation detail).

I hope it will help you.

**Comment by bmazzarol** [comment]
@StefanoMagrassi works for me, will close this in favour of #50 and eagerly await 6.0 release

**Pull request closed without merging**
