### PR TITLE
fix execution of initial commands when React view runs effect on mount

### PR DESCRIPTION
**Pull request by StefanoMagrassi**
This PR fixes the missing execution of initial commands when a `React` view runs effect (as command) on component mount.

The issue is related to the subscriptions timing in `run()`: the application subscribes to the `html$` stream **before** the `cmd$` stream.

Thus, if the view immediately dispatches a message that triggers a command (e.g. make a request on mount) this is added to the `cmd$` stream after the initial ones, making them unavailable when the application starts consuming the stream.

ref #40

### CODE REVIEW

**Comment by gcanti** [comment]
Thanks @StefanoMagrassi, the relevant bits seem:

- a change in `src/Platform.ts`
- a new test in `test/React.test.tsx` (named "should run the React Program - with commands in init and on component mount")

**Comment by StefanoMagrassi** [comment]
Any news on this PR? @minedeljkovic can you take a look, please?

**Comment by minedeljkovic** [comment]
> Any news on this PR? @minedeljkovic can you take a look, please?

@StefanoMagrassi I'm very sorry I was quiet about this, but I'm over my head busy at work these days. Since there are quite a few changes in this PR I cannot take as much time as I would need to understand everything properly.
That being said, your description makes perfect sense and if this is blocking anyone's work, please proceed with the merge without my review.

**Comment by StefanoMagrassi** [comment]
Ok @minedeljkovic don't worry. Thank you :+1: .

**Comment by gcanti** [comment]
Thanks @StefanoMagrassi

**Pull request merged**
